[[extensions]]
name = "t:collection_one_name"
handle = "pagekit-editor-extension-collection"
type = "editor_extension_collection"
uid = "14c8b172-a056-2b47-03fd-a9068c510bf92127b7bb"
# Add the handles of the extensions you want in this collection here
includes=[]

# You can also add extensions to the collection this way
#[[extensions.include]]
#handle=""

# A second editor extension collection added in the same extension toml config
# [[extensions]]
# name = "t:collection_two_name"
# type = "editor_extension_collection"
# handle = "pagekit-editor-extension-collection"
# includes=[]
