api_version = "2025-10"
[[extensions]]
name = "pagekit-admin-print"
handle = "pagekit-admin-print"
type = "ui_extension"
uid = "7d8fc6a0-a3da-f08b-8f67-03b8610bd757e5b73cbb"

# Only 1 target can be specified for each admin print action extension
[[extensions.targeting]]
module = "./src/PrintActionExtension.jsx"
target = "admin.order-details.print-action.render"

# Valid extension targets:

# - admin.order-details.print-action.render
# - admin.order-index.selection-print-action.render
# - admin.product-details.print-action.render
# - admin.product-index.selection-print-action.render
