api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "pagekit-cart-transformer"
type = "function"
uid = "d2c9212d-39b5-8882-93b0-410de22890bea269bd9a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
