api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "pagekit-delivery-customization"
type = "function"
uid = "ce225ede-b1a0-360c-8631-f96504aaf173007cb430"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
